version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

