version: '3.8'
services:
  frontend:
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
  backend:
    ports:
      - "8000:8000"
    env_file:
      - ./.env
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tajj
      - MONGO_INITDB_ROOT_PASSWORD=horsejumprightback
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: