version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm start
  backend:
    build:
      context: ./
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm start
