version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
  backend:
    build:
      context: ./
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tajj
      - MONGO_INITDB_ROOT_PASSWORD=horsejumprightback
    