version: '3.8'
services:
  backend:
    build: ./
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=production

  mongo:
    image: mongo
    ports:
      - "27017:27017"
