version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend_app
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    ports:
      - "5002:5000"

